import { Router } from "express";
import * as properties from "../minecraft/properties.js";
import * as rcon from "../rcon.js";
import { log } from "../logger.js";

const router = Router();

const DEFAULT_PROPERTIES = {
  "server-port": "25565",
  "server-ip": "",
  "motd": "Railway MC Server",
  "max-players": "20",
  "online-mode": "true",
  "white-list": "false",
  "enforce-whitelist": "false",
  "pvp": "true",
  "difficulty": "normal",
  "gamemode": "survival",
  "hardcore": "false",
  "view-distance": "6",
  "simulation-distance": "6",
  "spawn-protection": "16",
  "enable-rcon": "true",
  "rcon.port": "25575",
  "rcon.password": "changeme",
  "enable-command-block": "false",
  "allow-flight": "false",
  "allow-nether": "true",
  "generate-structures": "true",
  "spawn-animals": "true",
  "spawn-monsters": "true",
  "spawn-npcs": "true",
  "level-name": "world",
  "level-seed": "",
  "level-type": "minecraft:normal",
  "max-tick-time": "60000",
  "network-compression-threshold": "256",
  "resource-pack": "",
  "resource-pack-prompt": "",
};

const RESTART_REQUIRED_KEYS = new Set([
  "server-port",
  "server-ip",
  "level-name",
  "level-seed",
  "level-type",
  "online-mode",
  "white-list",
  "enforce-whitelist",
  "hardcore",
  "max-players",
  "view-distance",
  "simulation-distance",
  "max-tick-time",
  "enable-rcon",
  "rcon.port",
  "rcon.password",
  "network-compression-threshold",
]);

const LIVE_APPLY_MAP = {
  difficulty: (val) => `difficulty ${val}`,
  gamemode: (val) => `defaultgamemode ${val}`,
  pvp: (val) => `gamerule pvp ${val}`,
  "spawn-monsters": (val) => `gamerule doMobSpawning ${val}`,
  "spawn-animals": (val) => `gamerule doMobSpawning ${val}`,
  "spawn-npcs": (val) => `gamerule doMobSpawning ${val}`,
  "allow-flight": (val) => `gamerule allowFlight ${val}`,
  "allow-nether": () => null,
};

function serializeProperties(props) {
  const lines = [
    "# Minecraft server properties",
    `# Auto-generated by MC RailAdmin on ${new Date().toISOString()}`,
  ];
  for (const [key, value] of Object.entries(props)) {
    lines.push(`${key}=${value}`);
  }
  return lines.join("\n");
}

/**
 * GET /api/properties
 */
router.get("/", async (req, res) => {
  try {
    const values = await properties.readProperties();
    const merged = { ...DEFAULT_PROPERTIES, ...values };

    res.json({
      values: merged,
      defaults: DEFAULT_PROPERTIES,
      rawText: serializeProperties(merged),
    });
  } catch (err) {
    log.error("Failed to read server properties:", err.message);
    res.status(500).json({ error: err.message || "Failed to read properties" });
  }
});

/**
 * POST /api/properties
 */
router.post("/", async (req, res) => {
  try {
    const rawPayload = req.body || {};
    const inputValues = rawPayload.values || rawPayload;

    const current = await properties.readProperties();
    const liveApplied = [];
    const restartRequired = [];

    for (const [key, newVal] of Object.entries(inputValues)) {
      const oldVal = current[key];
      if (String(oldVal) !== String(newVal)) {
        if (RESTART_REQUIRED_KEYS.has(key)) {
          restartRequired.push(key);
        } else if (LIVE_APPLY_MAP[key]) {
          const cmd = LIVE_APPLY_MAP[key](newVal);
          if (cmd) {
            try {
              await rcon.send(cmd);
              liveApplied.push(key);
            } catch {
              restartRequired.push(key);
            }
          }
        }
      }
    }

    const updated = await properties.writeProperties(inputValues);
    const merged = { ...DEFAULT_PROPERTIES, ...updated };

    log.info(`Updated server.properties (${liveApplied.length} live applied, ${restartRequired.length} restart required)`);

    res.json({
      success: true,
      saved: true,
      liveApplied,
      restartRequired,
      values: merged,
      rawText: serializeProperties(merged),
    });
  } catch (err) {
    log.error("Failed to update server properties:", err.message);
    res.status(500).json({ error: err.message || "Failed to save properties" });
  }
});

/**
 * POST /api/properties/reset
 */
router.post("/reset", async (req, res) => {
  try {
    const { keys } = req.body || {};
    let partial = {};

    if (Array.isArray(keys) && keys.length > 0) {
      for (const k of keys) {
        if (DEFAULT_PROPERTIES[k] !== undefined) {
          partial[k] = DEFAULT_PROPERTIES[k];
        }
      }
    } else {
      partial = { ...DEFAULT_PROPERTIES };
    }

    const updated = await properties.writeProperties(partial);
    const merged = { ...DEFAULT_PROPERTIES, ...updated };

    res.json({
      success: true,
      values: merged,
      rawText: serializeProperties(merged),
    });
  } catch (err) {
    log.error("Failed to reset server properties:", err.message);
    res.status(500).json({ error: err.message || "Failed to reset properties" });
  }
});

/**
 * POST /api/properties/raw
 */
router.post("/raw", async (req, res) => {
  try {
    const { rawText } = req.body || {};
    if (typeof rawText !== "string") {
      return res.status(400).json({ error: "rawText string required" });
    }

    const lines = rawText.split("\n");
    const parsed = {};

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line || line.startsWith("#")) continue;

      const eqIdx = line.indexOf("=");
      if (eqIdx !== -1) {
        const key = line.slice(0, eqIdx).trim();
        const val = line.slice(eqIdx + 1).trim();
        if (key) {
          parsed[key] = val;
        }
      }
    }

    const updated = await properties.writeProperties(parsed);
    const merged = { ...DEFAULT_PROPERTIES, ...updated };

    res.json({
      success: true,
      values: merged,
      rawText: serializeProperties(merged),
    });
  } catch (err) {
    log.error("Failed to write raw server properties:", err.message);
    res.status(500).json({ error: err.message || "Failed to write raw properties" });
  }
});

export default router;
