/**
 * Curated list of popular Minecraft plugins for one-tap store installation
 */
export const CURATED_PLUGIN_STORE = [
  {
    id: 'essentialsx',
    name: 'EssentialsX',
    version: '2.20.1',
    size: '4.2 MB',
    author: 'EssentialsX Team',
    description: 'The essential plugin suite providing teleportation, economy, homes, warps, moderation, and player management tools.',
    commands: ['/essentials', '/home', '/sethome', '/spawn', '/warp', '/msg', '/tpa', '/tpaccept'],
    permissions: ['essentials.home', 'essentials.warp', 'essentials.tpa', 'essentials.teleport'],
    dependencies: ['Vault'],
    apiVersion: '1.20',
    loadOrder: 'POSTWORLD',
  },
  {
    id: 'luckperms',
    name: 'LuckPerms',
    version: '5.4.102',
    size: '3.8 MB',
    author: 'Luck',
    description: 'An advanced, high-performance permissions plugin for Minecraft servers with web editor and fast SQL/file caching.',
    commands: ['/lp', '/luckperms', '/lp user', '/lp group'],
    permissions: ['luckperms.admin', 'luckperms.user.info'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'STARTUP',
  },
  {
    id: 'vault',
    name: 'Vault',
    version: '1.7.3',
    size: '380 KB',
    author: 'Sleaker',
    description: 'Universal abstraction API hook for chat formatting, player permissions, and in-game economy plugins.',
    commands: ['/vault', '/vault-info'],
    permissions: ['vault.admin'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'STARTUP',
  },
  {
    id: 'worldedit',
    name: 'WorldEdit',
    version: '7.3.0',
    size: '5.1 MB',
    author: 'EngineHub',
    description: 'In-game Minecraft map editor and world manipulator. Create, copy, paste, rotate, and terraform with ease.',
    commands: ['//wand', '//set', '//copy', '//paste', '//undo', '//redo', '//brush', '//replace'],
    permissions: ['worldedit.wand', 'worldedit.selection', 'worldedit.generation'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'NORMAL',
  },
  {
    id: 'worldguard',
    name: 'WorldGuard',
    version: '7.0.9',
    size: '2.9 MB',
    author: 'EngineHub',
    description: 'Powerful region protection and flag system. Prevent griefing, restrict PvP in spawn, and protect safe zones.',
    commands: ['/rg', '/region', '/region define', '/region flag'],
    permissions: ['worldguard.region.define', 'worldguard.region.flag'],
    dependencies: ['WorldEdit'],
    apiVersion: '1.20',
    loadOrder: 'POSTWORLD',
  },
  {
    id: 'placeholderapi',
    name: 'PlaceholderAPI',
    version: '2.11.5',
    size: '420 KB',
    author: 'HelpChat',
    description: 'High-performance placeholder parsing framework connecting scoreboard, tab list, and chat plugins.',
    commands: ['/papi', '/papi ecloud', '/papi reload'],
    permissions: ['papi.admin'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'STARTUP',
  },
  {
    id: 'viaversion',
    name: 'ViaVersion',
    version: '4.9.2',
    size: '2.4 MB',
    author: 'Gerrygames & Formally',
    description: 'Allows newer Minecraft client versions to connect smoothly to older server protocol versions.',
    commands: ['/viaver', '/viaversion'],
    permissions: ['viaversion.admin'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'STARTUP',
  },
  {
    id: 'coreprotect',
    name: 'CoreProtect',
    version: '22.2',
    size: '1.8 MB',
    author: 'Intelli',
    description: 'Fast, efficient data logging and anti-griefing tool. Inspect block edits, rollback griefers, and restore containers.',
    commands: ['/co', '/co inspect', '/co rollback', '/co restore'],
    permissions: ['coreprotect.inspect', 'coreprotect.rollback'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'POSTWORLD',
  },
  {
    id: 'dynmap',
    name: 'Dynmap',
    version: '3.7-beta',
    size: '6.5 MB',
    author: 'mikeprimm',
    description: 'Real-time Google Maps-like web map for your Minecraft server showing terrain, players, and structures.',
    commands: ['/dynmap', '/dynmap render', '/dynmap fullrender'],
    permissions: ['dynmap.admin', 'dynmap.render'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'POSTWORLD',
  },
  {
    id: 'voicechat',
    name: 'Simple Voice Chat',
    version: '2.5.8',
    size: '3.1 MB',
    author: 'henkelmax',
    description: 'Proximity voice chat plugin for Minecraft. Talk in real-time with nearby players directly in-game.',
    commands: ['/voicechat', '/voicechat test'],
    permissions: ['voicechat.speak', 'voicechat.listen'],
    dependencies: [],
    apiVersion: '1.20',
    loadOrder: 'NORMAL',
  },
];
